### ISSUE TITLE
树莓派镜像还原问题

### ISSUE THREAD

**Issue by white-li** [Neutree/note#5]
抱歉打扰，通过你的教程制作的镜像 backup.img，还原方式可以详细说下吗？
在树莓派环境中，是使用以下命令吗？（我的磁盘）
sudo dd if=backup.img of=/dev/sd* 
树莓派中对应目录为 /dev/root 和 /dev/mmcblk0p1，为什么 of=/dev/sd*  ?请指点

那如果我在外部环境是否可以直接用 applePi-Baker 工具烧录镜像？
谢谢！~

**Comment by Neutree** [comment]
还原备份的镜像`* .img`到SD卡和你第一次给树莓派装系统的方式是一样的

这里`sudo dd if=backup.img of=/dev/sd*`这句话不是在树莓派中执行的，而是需要在PC的linux系统（你说的外部环境）中执行，这个`/dev/sd*`设备就是你插到电脑上的SD卡设备

windows下用`win32diskimager`是可以的

mac下`applePi-Baker`估计也可以吧，买不起mac哈哈哈哈，反正如果你用`applePi-Baker`给树莓派成功安装过系统那就可以

**Comment by white-li** [comment]
谢谢！！！

**Comment by Neutree** [comment]
不客气，回复完后记得扩展一下分区
